[DNM] Diffs download
vmihaylenko/omim pull request #12
Opened 2017-08-09 16:14 UTC by VladiMihaylenko

2017-08-09 16:15 UTC, VladiMihaylenko commented
@milchakov ptal
@ygorshenin ptal

2017-08-09 17:14 UTC, rokuz commented on storage/storage.cpp
> +  if (!download.empty())
Этот код практически полностью дублируется ниже

2017-08-09 17:14 UTC, rokuz commented on storage/storage.cpp
> +                                             bind(&Storage::OnServerListDownloaded, this, urls));
std::bind

2017-08-09 18:36 UTC, bykoianko commented on storage/storage.cpp
> +                                             bind(&Storage::OnServerListDownloaded, this, urls));
В это файле ```#include "std/....```. Думаю стоит добавить ```#include <future>```, на верху написать using namespace std; и тогда в это .cpp убрать ```std::```. Или как вариант, добавить ```#include <future>``` и оставить std:: только перед тем, что пришло от него.

2017-08-09 18:37 UTC, bykoianko commented on storage/storage.hpp
> +  void DownloadNode(TCountryId const & countryId, bool isUpdate = false);
Наверно стоит уточнить комментарий.

2017-08-09 18:37 UTC, bykoianko commented on storage/storage.hpp
> +  string GetFileDownloadUrl(string const & baseUrl, QueuedCountry const & queuedCountry) const;
Наверно стоит уточнить комментарий.

2017-08-09 18:39 UTC, bykoianko commented on storage/storage.cpp
> +                                             bind(&Storage::OnServerListDownloaded, this, urls));
Вижу ```#include <future>``` уже в h файле. Вроде все ок, но надо выровнять.

2017-08-09 18:40 UTC, bykoianko commented on map/framework.cpp
> +             : DoAfterUpdate::AskForUpdateMaps;
clang-format?

2017-08-09 18:41 UTC, bykoianko commented on storage/storage.cpp
> +  if (!download.empty())
+1

2017-08-09 18:48 UTC, VladiMihaylenko commented on map/framework.cpp
> +             : DoAfterUpdate::AskForUpdateMaps;
ok

2017-08-09 18:48 UTC, VladiMihaylenko commented on storage/storage.hpp
> +  string GetFileDownloadUrl(string const & baseUrl, QueuedCountry const & queuedCountry) const;
ok

2017-08-09 18:49 UTC, VladiMihaylenko commented on storage/storage.hpp
> +  void DownloadNode(TCountryId const & countryId, bool isUpdate = false);
ok

2017-08-09 18:49 UTC, VladiMihaylenko commented on storage/storage.cpp
> +                                             bind(&Storage::OnServerListDownloaded, this, urls));
ok, выровняю

2017-08-09 18:49 UTC, VladiMihaylenko commented on storage/storage.cpp
> +  if (!download.empty())
исправлю

2017-08-09 19:43 UTC, mpimenov commented on storage/storage.hpp
> +  /// Returns true if the diff scheme is available and the all local outdated maps have possibility to update via diffs.
s/the all/all/

2017-08-09 19:43 UTC, mpimenov commented on storage/storage.hpp
> +  /// Returns true if the diff scheme is available and the all local outdated maps have possibility to update via diffs.
s/have possibility to update/can be updated/

2017-08-09 19:43 UTC, mpimenov commented on storage/storage.hpp
> +  std::future<void> m_defferedUpdateTask;
Имеет смысл вынести в общую структуру типа DiffApplier?

2017-08-09 19:43 UTC, mpimenov commented on storage/storage.cpp
> +    return true;
s/true/false/

2017-08-10 05:42 UTC, rokuz commented on storage/storage.cpp
> +      m_defferedUpdateTask.get();
Кажется, get() может кинуть исключение std::future_error. Если сейчас он это сделает, то приложение крэшнится

2017-08-10 05:42 UTC, rokuz commented on storage/storage.cpp
> +      m_defferedUpdateTask.get();
@ygorshenin проконсультируй, плиз, по этому поводу

2017-08-10 06:44 UTC, bykoianko commented on storage/storage.cpp
> +    fn(countryId, false);
Please add inline comment for false.

2017-08-10 06:46 UTC, bykoianko commented on storage/storage.cpp
> +  return url + "/" + UrlEncode(fileName);
Не будет удобнее со stringstream при формировании строк?

2017-08-10 06:46 UTC, bykoianko commented on storage/storage.cpp
> +    url += /*OMIM_OS_NAME "/" +*/ currentVersion;
Удалим коммент?

2017-08-10 06:47 UTC, bykoianko commented on storage/storage.cpp
> +    return;;
Две ;

2017-08-10 08:08 UTC, milchakov commented on map/framework.cpp
> +  return connectionStatus == Platform::EConnectionType::CONNECTION_WIFI && isPossibleToAutoupdate
Кажется, лучше так:
```
auto const autoUpdate = connectionStatus == Platform::EConnectionType::CONNECTION_WIFI && s.IsPossibleToAutoupdate();

return autoUpdate ? DoAfterUpdate::AutoupdateMaps : DoAfterUpdate::AskForUpdateMaps;
```

2017-08-10 08:10 UTC, milchakov commented on storage/storage.cpp
> +#include "storage/diff_scheme/diff_scheme_checker.hpp"
отсортируй инклуды, пожалуйста

2017-08-10 08:13 UTC, milchakov commented on storage/storage.cpp
> +char const kDownloadQueueKey[] = "DownloadQueue";
а зачем именно массив создавать? тебе нужно узнавать его длину?

2017-08-10 08:15 UTC, VladiMihaylenko commented on storage/storage.cpp
> +#include "storage/diff_scheme/diff_scheme_checker.hpp"
ок

2017-08-10 08:16 UTC, VladiMihaylenko commented on storage/storage.cpp
> +char const kDownloadQueueKey[] = "DownloadQueue";
а что вместо? char const * char?

2017-08-10 08:16 UTC, VladiMihaylenko commented on map/framework.cpp
> +  return connectionStatus == Platform::EConnectionType::CONNECTION_WIFI && isPossibleToAutoupdate
ok

2017-08-10 08:17 UTC, VladiMihaylenko commented on storage/storage.cpp
> +    return;;
ok

2017-08-10 08:19 UTC, VladiMihaylenko commented on storage/storage.cpp
> +    url += /*OMIM_OS_NAME "/" +*/ currentVersion;
хорошо

2017-08-10 08:19 UTC, VladiMihaylenko commented on storage/storage.cpp
> +  return url + "/" + UrlEncode(fileName);
да, наверное, стоит переделать

2017-08-10 08:19 UTC, VladiMihaylenko commented on storage/storage.cpp
> +      m_defferedUpdateTask.get();
по идеи, если valid() вернул true - проблем не должно быть

2017-08-10 08:19 UTC, VladiMihaylenko commented on storage/storage.cpp
> +    return true;
ok

2017-08-10 08:21 UTC, VladiMihaylenko commented on storage/storage.hpp
> +  /// Returns true if the diff scheme is available and the all local outdated maps have possibility to update via diffs.
ok

2017-08-10 08:24 UTC, milchakov commented on storage/storage.cpp
> +    while (iter)
Может так?
```
for (strings::SimpleTokenizer iter(download, ";"); iter; ++iter)
{
}
```

2017-08-10 08:44 UTC, milchakov commented on storage/storage.cpp
> +      m_defferedUpdateTask.get();
Допиши пожалуйста в начало метода проверку, что коллбэк вызван на главном потоке

2017-08-10 09:14 UTC, VladiMihaylenko commented on storage/storage.cpp
> +    fn(countryId, false);
ok

2017-08-10 09:19 UTC, ygorshenin commented on storage/storage.cpp
> +char const kDownloadQueueKey[] = "DownloadQueue";
@milchakov, разницы между const char * и const char[] особо никакой, но последняя форма действительно предполагает constant time sizeof, так почему бы не использовать ее?

2017-08-10 09:50 UTC, VladiMihaylenko commented on storage/storage.cpp
> +      m_defferedUpdateTask.get();
@milchakov готово

2017-08-10 09:59 UTC, milchakov commented on storage/storage.cpp
> +        m_diffSchemeStatus = diff_scheme::Status::NotAvailable;
гонка на m_diffSchemeStatus

2017-08-10 10:06 UTC, milchakov commented on storage/storage.cpp
> +  diff_scheme::Checker::Check(localMapsInfo, [this](diff_scheme::NameFileInfoMap const & diffs) {
Думаю, самым простым способом решить проблему обращения к мемберам тогда, когда this уже уничтожено - не детачить поток в методе check, добавить в чекер мембера WorkerThread и положить Checker в Storage.

2017-08-10 10:08 UTC, VladiMihaylenko commented on storage/storage.cpp
> +        m_diffSchemeStatus = diff_scheme::Status::NotAvailable;
да, верно. перенесу установку в главный поток

2017-08-10 10:08 UTC, VladiMihaylenko commented on storage/storage.cpp
> +  diff_scheme::Checker::Check(localMapsInfo, [this](diff_scheme::NameFileInfoMap const & diffs) {
мне кажется, не стоит запариваться. много получится лишних движений, не совсем понятно, ради чего

2017-08-10 10:45 UTC, milchakov commented on storage/storage.hpp
> +  std::future<void> m_defferedUpdateTask;
+1 и, если выносить в отдельную структуру, можно не использовать future, а просто function. Однократный вызов метода может гарантироваться тем, что задача будет поститься на поток в конструкторе этой новой структурки

2017-08-10 10:48 UTC, VladiMihaylenko commented on storage/storage.hpp
> +  std::future<void> m_defferedUpdateTask;
я согласен. 
только не совсем понятно, чем плох фьючер

2017-08-10 11:16 UTC, mpimenov commented on map/framework.cpp
> +  return isPossibleToAutoupdate ? DoAfterUpdate::AutoupdateMaps : DoAfterUpdate::AskForUpdateMaps;
```
if (s.IsPossibleToAutoupdate() && connectionStatus == Platform::EConnectionType::CONNECTION_WIFI)
  return DoAfterUpdate::AutoupdateMaps;

return DoAfterUpdate::AskForUpdateMaps;
```

2017-08-10 11:16 UTC, mpimenov commented on storage/storage.cpp
> +#include "generator/mwm_diff/diff.hpp"
Надо поставить перед coding.

2017-08-10 11:18 UTC, milchakov commented on storage/storage.cpp
> +char const kDownloadQueueKey[] = "DownloadQueue";
@ygorshenin а зачем ее использовать, если нигде не требуется? И я не говорил про `const char *`, мое предложение `auto const`.

2017-08-10 11:19 UTC, milchakov commented on storage/storage.cpp
> +    while (iter)
пинг

2017-08-10 11:20 UTC, VladiMihaylenko commented on storage/storage.cpp
> +char const kDownloadQueueKey[] = "DownloadQueue";
тогда будет string

2017-08-10 11:21 UTC, VladiMihaylenko commented on map/framework.cpp
> +  return isPossibleToAutoupdate ? DoAfterUpdate::AutoupdateMaps : DoAfterUpdate::AskForUpdateMaps;
ok

2017-08-10 11:21 UTC, VladiMihaylenko commented on storage/storage.cpp
> +#include "generator/mwm_diff/diff.hpp"
ok

2017-08-10 12:36 UTC, ygorshenin commented on storage/storage.cpp
> +char const kDownloadQueueKey[] = "DownloadQueue";
@milchakov, из двух равных по затратам альтернатив почему бы не выбрать ту где больше возможностей?

2017-08-10 12:36 UTC, milchakov commented on storage/storage.cpp
> +char const kDownloadQueueKey[] = "DownloadQueue";
да, Set как раз принимает ссылку на строку

2017-08-10 12:42 UTC, ygorshenin commented on storage/storage.cpp
> +      m_defferedUpdateTask =
deferred?

2017-08-10 12:57 UTC, ygorshenin commented on storage/storage.cpp
> +      bool const res = ApplyDiff(countryId);
```c++
auto const success = ...
```

2017-08-10 12:58 UTC, ygorshenin commented on storage/storage.cpp
> +  if (files == MapOptions::Diff)
```c++
if (files != MapOptions::Diff)
  return;
...
```

2017-08-10 12:59 UTC, ygorshenin commented on storage/storage.cpp
> +          // TODO: Log the diff applying error.
И еще удалить diff надо.

2017-08-10 13:00 UTC, ygorshenin commented on storage/storage.cpp
> +  if (files == MapOptions::Diff)
А, все ОКю

2017-08-10 13:23 UTC, VladiMihaylenko commented on storage/storage.cpp
> +          // TODO: Log the diff applying error.
он удаляется в ApplyDiff

2017-08-10 13:24 UTC, VladiMihaylenko commented on storage/storage.cpp
> +    while (iter)
да, ок.
хз почему потерлось

2017-08-10 13:36 UTC, VladiMihaylenko commented on storage/storage.cpp
> +      m_defferedUpdateTask =
да

2017-08-10 13:36 UTC, VladiMihaylenko commented on storage/storage.cpp
> +      bool const res = ApplyDiff(countryId);
ок

2017-08-10 13:38 UTC, ygorshenin requested changes

2017-08-10 13:38 UTC, ygorshenin commented on storage/storage.cpp
> +                               {"option", DebugPrint(files)}}));
Нене, никаких DebugPrint в статистике.

2017-08-10 13:38 UTC, ygorshenin commented on storage/storage.cpp
> +  ASSERT_THREAD_CHECKER(m_threadChecker, ());
This should be first.

2017-08-10 13:38 UTC, ygorshenin commented on storage/storage.cpp
> +  stringstream download;
ostringstream?

2017-08-10 13:38 UTC, ygorshenin commented on storage/storage.cpp
> +    m_failedCountries.insert(countryId);
Зачем? Почему не позвать OnMapDownloadFinished()? А в нем LogEventOnDownloadFinished()? К тому же там осталась логика с m_failedCountries.

2017-08-10 13:38 UTC, ygorshenin commented on storage/storage.cpp
> +      m_defferedUpdateTask =
Why? We just get urls, why do we need to asynchronously call OnServerListDownloaded again?

2017-08-10 13:38 UTC, ygorshenin commented on storage/storage.cpp
> +bool Storage::IsPossibleToAutoupdate() const
Это не IsPossibleToAutoupdate. Это HasOutOfDateMaps.

2017-08-10 13:47 UTC, rokuz approved these changes

2017-08-10 13:48 UTC, VladiMihaylenko commented on storage/storage.cpp
> +  return url + "/" + UrlEncode(fileName);
оставлю наверное сейчас код так, как было написано в оригинале, если ты не против

2017-08-10 13:49 UTC, VladiMihaylenko commented on storage/storage.cpp
> +  ASSERT_THREAD_CHECKER(m_threadChecker, ());
ok

2017-08-10 13:50 UTC, VladiMihaylenko commented on storage/storage.cpp
> +  stringstream download;
ok

2017-08-10 13:52 UTC, VladiMihaylenko commented on storage/storage.cpp
> +    m_failedCountries.insert(countryId);
да, теперь можно. забыл переделать обратно

2017-08-10 13:54 UTC, VladiMihaylenko commented on storage/storage.cpp
> +                               {"option", DebugPrint(files)}}));
это код, который не я писал. могу продублировать дебаг принт, чтобы определить строковую константу, выше

2017-08-10 14:04 UTC, VladiMihaylenko commented
@milchakov @mpimenov @bykoianko @ygorshenin ptal

2017-08-10 14:48 UTC, ygorshenin commented
LGTM, but there may be more comments later. Will resolve possible issues with @milchakov.

2017-08-10 19:51 UTC, ygorshenin commented on storage/diff_scheme/diff_scheme_checker.cpp
> +#include <unordered_map>
Sort, please.

2017-08-10 19:52 UTC, ygorshenin commented on storage/diff_scheme/diff_manager.hpp
> +
No need in this blank line.

2017-08-10 19:52 UTC, ygorshenin commented on storage/diff_scheme/diff_manager.hpp
> +  std::future<void> m_deferredUpdateTask;
Exhaustive comment to the field, please.

2017-08-10 19:53 UTC, ygorshenin commented on storage/diff_scheme/diff_manager.hpp
> +  void ApplyDiff(std::function<void()> && task) { m_workerThread.Push(std::move(task)); }
Why not perfect forwarding?

2017-08-10 19:56 UTC, ygorshenin commented on storage/storage.cpp
> +      m_diffManager.SetDeferredUpdateTask(std::async(std::launch::deferred,
So, if m_diffManager.Status() is undefined, you defer call to the method. But why not use Observers? Looks like this is a hacky version, why not to rewrite this to clean Observers? I mean, you need to add Observer interface to the diff manager, and then subscribe here.

2017-08-10 19:57 UTC, ygorshenin commented on storage/diff_scheme/diff_manager.hpp
> +  void ApplyDiff(std::function<void()> && task) { m_workerThread.Push(std::move(task)); }
Please, rename this to PushOnWorkerThread, because the user of the function may push ANY task here.

2017-08-10 19:58 UTC, ygorshenin commented on storage/diff_scheme/diff_manager.hpp
> +  void SetDeferredUpdateTask(std::future<void> && task) { m_deferredUpdateTask = std::move(task); }
Please, rewrite to Observers. Current version is extremely inefficient and hacky.

2017-08-11 07:46 UTC, milchakov commented on storage/diff_scheme/diff_scheme_checker.cpp
> +#include <unordered_map>
не, понял, тут все отсортировано

2017-08-11 07:47 UTC, milchakov commented on storage/diff_scheme/diff_manager.hpp
> +
удалил

2017-08-17 12:17 UTC, milchakov commented on storage/diff_scheme/diff_manager.hpp
> +  std::future<void> m_deferredUpdateTask;
удалил это поле

2017-08-17 12:17 UTC, milchakov commented on storage/diff_scheme/diff_manager.hpp
> +  void ApplyDiff(std::function<void()> && task) { m_workerThread.Push(std::move(task)); }
переделал метод

2017-08-17 12:18 UTC, milchakov commented on storage/storage.cpp
> +      m_diffManager.SetDeferredUpdateTask(std::async(std::launch::deferred,
воспользовался твоим советом

2017-08-17 12:18 UTC, milchakov commented on storage/diff_scheme/diff_manager.hpp
> +  void SetDeferredUpdateTask(std::future<void> && task) { m_deferredUpdateTask = std::move(task); }
сделано

2017-09-14 08:22 UTC, closed without merging